# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXg2Uw6vJcFLzP3oBOkSxVBn-m4essNV
"""

import os, re, json, argparse, tempfile, subprocess, random
from typing import Optional, Tuple, List, Dict, Any
from datasets import load_from_disk, Dataset, DatasetDict

SPACE = re.compile(r"\s+")
IDLIKE = re.compile(r"\b([a-zA-Z])\b")

def norm(s: str) -> str:
    s = s.replace("\\forall", "∀").replace("\\exists", "∃").replace("\\to", "→").replace("\\iff", "↔")
    s = s.replace("\\land", "∧").replace("\\lor", "∨").replace("\\neg", "¬")
    s = s.replace("\\mathbb{N}", "Nat").replace("ℕ", "Nat").replace("\\mathbb{Z}", "Int").replace("ℤ", "Int")
    s = s.replace("\\mathbb{Q}", "Rat").replace("ℚ", "Rat").replace("\\mathbb{R}", "Real").replace("ℝ", "Real")
    s = s.replace("$", "")
    s = SPACE.sub(" ", s).strip()
    return s

# detectors return (goal, tactic, imports)

def det_true(s: str) -> Optional[Tuple[str, str, List[str]]]:
    if re.search(r"\bTrue\b", s):
        return "True", "trivial", ["Std"]
    return None

def det_false_imp_false(s: str) -> Optional[Tuple[str, str, List[str]]]:
    if re.search(r"\bFalse\s*→\s*False\b", s):
        return "False → False", "intro h; exact h", ["Std"]
    return None

def det_and_left(s: str) -> Optional[Tuple[str, str, List[str]]]:
    # catches "P ∧ Q → P" style
    if re.search(r"\b∧\b.*→", s):
        P, Q = "P", "Q"
        return f"∀ {P} {Q} : Prop, {P} ∧ {Q} → {P}", "intro P; intro Q; intro h; exact h.left", ["Std"]
    return None

def det_impl_refl(s: str) -> Optional[Tuple[str, str, List[str]]]:
    # P → P
    if re.search(r"\b([A-Z])\s*→\s*\1\b", s):
        return "∀ P : Prop, P → P", "intro P; intro h; exact h", ["Std"]
    return None

def det_eq_refl(s: str) -> Optional[Tuple[str, str, List[str]]]:
    # a = a
    m = re.search(r"\b([a-zA-Z])\s*=\s*\1\b", s)
    if m:
        a = m.group(1)
        return f"∀ {a} : Nat, {a} = {a}", f"intro {a}; rfl", ["Std"]
    return None

def det_add_comm_nat(s: str) -> Optional[Tuple[str, str, List[str]]]:
    # a + b = b + a
    if re.search(r"\b([a-zA-Z])\s*\+\s*([a-zA-Z])\s*=\s*\2\s*\+\s*\1\b", s):
        return "∀ a b : Nat, a + b = b + a", "intros; rw [Nat.add_comm]", ["Std"]
    return None

def det_mul_comm_nat(s: str) -> Optional[Tuple[str, str, List[str]]]:
    # a * b = b * a
    if re.search(r"\b([a-zA-Z])\s*\*\s*([a-zA-Z])\s*=\s*\2\s*\*\s*\1\b", s):
        return "∀ a b : Nat, a * b = b * a", "intros; rw [Nat.mul_comm]", ["Std"]
    return None

def det_add_assoc_nat(s: str) -> Optional[Tuple[str, str, List[str]]]:
    # (a + b) + c = a + (b + c)
    if re.search(r"\(\s*[a-zA-Z]\s*\+\s*[a-zA-Z]\s*\)\s*\+\s*[a-zA-Z]\s*=\s*[a-zA-Z]\s*\+\s*\(\s*[a-zA-Z]\s*\+\s*[a-zA-Z]\s*\)", s):
        return "∀ a b c : Nat, (a + b) + c = a + (b + c)", "intros; rw [Nat.add_assoc]", ["Std"]
    return None

def det_add_zero_nat(s: str) -> Optional[Tuple[str, str, List[str]]]:
    # a + 0 = a or 0 + a = a
    if re.search(r"\b([a-zA-Z])\s*\+\s*0\s*=\s*\1\b", s):
        return "∀ a : Nat, a + 0 = a", "intro a; simp", ["Std"]
    if re.search(r"\b0\s*\+\s*([a-zA-Z])\s*=\s*\1\b", s):
        return "∀ a : Nat, 0 + a = a", "intro a; simp", ["Std"]
    return None

def det_le_total_nat(s: str) -> Optional[Tuple[str, str, List[str]]]:
    # mentions inequality compare a and b
    if re.search(r"\b≤|>=|≥|<|>\b", s) and re.search(r"\bNat\b|\bnatural\b|\bℕ\b", s, re.I):
        return "∀ a b : Nat, a ≤ b ∨ b ≤ a", "intros; apply le_total", ["Std"]
    return None

def det_sum_first_n(s: str) -> Optional[Tuple[str, str, List[str]]]:
    # common phrasing: sum of first n integers
    if re.search(r"sum of the first n (integers|numbers)", s, re.I):
        goal = "∀ n : Nat, ∑ i in Finset.range (n+1), i = n*(n+1)/2"
        tactic = "intro n; simpa [Finset.sum_range_id, Nat.succ_eq_add_one, two_mul, Nat.mul_add, Nat.add_mul, Nat.mul_comm, Nat.mul_left_comm, Nat.add_comm, Nat.add_left_comm]"
        return goal, tactic, ["Std", "Mathlib"]
    return None

def det_sets_union_comm(s: str) -> Optional[Tuple[str, str, List[str]]]:
    # A ∪ B = B ∪ A
    if re.search(r"\b∪\b", s) and re.search(r"commutative|commutes|order does not matter", s, re.I):
        goal = "∀ (A B : Set Nat), A ∪ B = B ∪ A"
        tactic = "intro A; intro B; ext x; simp [Set.union_comm]"
        return goal, tactic, ["Std", "Mathlib"]
    return None

def det_sets_inter_subset_left(s: str) -> Optional[Tuple[str, str, List[str]]]:
    # A ∩ B ⊆ A
    if re.search(r"subset|⊆", s, re.I) and re.search(r"∩", s):
        goal = "∀ (A B : Set Nat), A ∩ B ⊆ A"
        tactic = "intro A; intro B; intro x; intro hx; exact hx.left"
        return goal, tactic, ["Std", "Mathlib"]
    return None

def det_comp_id(s: str) -> Optional[Tuple[str, str, List[str]]]:
    # (f ∘ id) x = f x
    if re.search(r"\b∘\b|\bcomposition\b", s):
        goal = "∀ (α β : Type) (f : α → β) (x : α), (f ∘ id) x = f x"
        tactic = "intro α; intro β; intro f; intro x; rfl"
        return goal, tactic, ["Std", "Mathlib"]
    return None

DETECTORS = [
    det_sum_first_n,
    det_sets_union_comm,
    det_sets_inter_subset_left,
    det_comp_id,
    det_add_comm_nat,
    det_mul_comm_nat,
    det_add_assoc_nat,
    det_add_zero_nat,
    det_le_total_nat,
    det_eq_refl,
    det_impl_refl,
    det_and_left,
    det_false_imp_false,
    det_true,
]

def lean_ok(goal: str, tactic: str, imports: List[str], timeout: float) -> Tuple[bool, str]:
    lines = []
    for m in imports:
        lines.append(f"import {m}")
    lines += [
        "",
        "set_option maxHeartbeats 400000",
        "set_option linter.unusedVariables false",
        f"example : {goal} := by",
        f"  {tactic}",
        "",
    ]
    code = "\n".join(lines)
    with tempfile.TemporaryDirectory() as td:
        src = os.path.join(td, "Check.lean")
        with open(src, "w", encoding="utf-8") as f:
            f.write(code)
        try:
            r = subprocess.run(["lean", src], capture_output=True, text=True, timeout=timeout)
            return (r.returncode == 0, (r.stderr or "").strip())
        except subprocess.TimeoutExpired:
            return (False, f"timeout>{timeout}s")

def try_convert(rec: Dict[str, Any], allow_mathlib: bool, timeout: float) -> Optional[Dict[str, Any]]:

    texts = []
    for k in ("text", "target", "title"):
        if k in rec and rec[k]:
            texts.append(norm(str(rec[k])))

    for s in texts:
        for det in DETECTORS:
            goal, tac, imps = (None, None, None)
            out = det(s)
            if not out:
                continue
            goal, tac, imps = out
            if not allow_mathlib:
                imps = [m for m in imps if m != "Mathlib"]
            ok, _ = lean_ok(goal, tac, imps, timeout)
            if ok:
                return {
                    "id": rec.get("id", None),
                    "goal": goal,
                    "gold_tactic": tac,
                    "imports": imps
                }
    return None

def convert_split(records, allow_mathlib: bool, timeout: float) -> Tuple[Dataset, Dict[str,int]]:
    kept, skipped = 0, 0
    out: List[Dict[str, Any]] = []
    for rec in records:
        conv = try_convert(rec, allow_mathlib=allow_mathlib, timeout=timeout)
        if conv:
            out.append(conv)
            kept += 1
        else:
            skipped += 1
    stats = {"kept": kept, "skipped": skipped}
    return Dataset.from_list(out) if out else Dataset.from_list([]), stats

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--np_root", required=True, help="hf dataset path for naturalproofs (load_from_disk)")
    ap.add_argument("--out_root", required=True, help="output path for converted, verified dataset")
    ap.add_argument("--timeout", type=float, default=6.0, help="lean timeout per example in seconds")
    ap.add_argument("--seed", type=int, default=0, help="rng seed")
    ap.add_argument("--no_mathlib", action="store_true", help="disable Mathlib import; use Std only")
    args = ap.parse_args()

    random.seed(args.seed)
    allow_mathlib = not args.no_mathlib

    ds_src = load_from_disk(args.np_root)
    splits: Dict[str, Dataset] = {}
    stats: Dict[str, Dict[str,int]] = {}

    for sp in ["train", "validation", "test"]:
        if sp not in ds_src: continue
        print(f"[split] {sp} rows={len(ds_src[sp])}")
        ds_out, s = convert_split(ds_src[sp], allow_mathlib=allow_mathlib, timeout=args.timeout)
        splits[sp] = ds_out
        stats[sp] = s


    splits = {k: v for k, v in splits.items() if len(v) > 0}
    if not splits:
        raise SystemExit("no convertible examples were found; check mathlib availability or widen detectors")

    out = DatasetDict(splits)
    os.makedirs(args.out_root, exist_ok=True)
    out.save_to_disk(args.out_root)

    report = {"splits": stats, "out_root": args.out_root, "mathlib": allow_mathlib}
    with open(os.path.join(args.out_root, "conversion_report.json"), "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)
    print(json.dumps(report, indent=2))

if __name__ == "__main__":
    main()