# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KXg2Uw6vJcFLzP3oBOkSxVBn-m4essNV
"""

import os, re, json, argparse, tempfile, subprocess, random
from typing import Optional, Tuple, Dict, Any, List
from datasets import load_from_disk, Dataset, DatasetDict

# normalization

SPACE = re.compile(r"\s+")
def norm(s: str) -> str:
    s = s.replace("\\forall", "∀").replace("\\exists", "∃").replace("\\to", "→").replace("\\iff", "↔")
    s = s.replace("\\land", "∧").replace("\\lor", "∨").replace("\\neg", "¬")
    s = s.replace("\\mathbb{N}", "Nat").replace("ℕ", "Nat").replace("\\mathbb{Z}", "Int").replace("ℤ", "Int")
    s = s.replace("\\mathbb{Q}", "Rat").replace("ℚ", "Rat").replace("\\mathbb{R}", "Real").replace("ℝ", "Real")
    s = s.replace(": $", ": ").replace("$", "")
    s = SPACE.sub(" ", s).strip()
    return s

# detectors from text to lean goal and tactic

V = "abcdefghijklmnopqrstuvwxyz"

def eq_comm_add_nat(s: str) -> Optional[Tuple[str, str, List[str]]]:
    m = re.search(r"\b([a-zA-Z])\s*\+\s*([a-zA-Z])\s*=\s*\2\s*\+\s*\1\b", s)
    if not m: return None
    a, b = m.group(1), m.group(2)
    goal = f"∀ {a} {b} : Nat, {a} + {b} = {b} + {a}"
    tac  = f"intro {a}; intro {b}; rw [Nat.add_comm]"
    return goal, tac, ["Std"]

def eq_comm_mul_nat(s: str) -> Optional[Tuple[str, str, List[str]]]:
    m = re.search(r"\b([a-zA-Z])\s*\*\s*([a-zA-Z])\s*=\s*\2\s*\*\s*\1\b", s)
    if not m: return None
    a, b = m.group(1), m.group(2)
    goal = f"∀ {a} {b} : Nat, {a} * {b} = {b} * {a}"
    tac  = f"intro {a}; intro {b}; rw [Nat.mul_comm]"
    return goal, tac, ["Std"]

def eq_assoc_add_nat(s: str) -> Optional[Tuple[str, str, List[str]]]:
    m = re.search(r"\(\s*([a-zA-Z])\s*\+\s*([a-zA-Z])\s*\)\s*\+\s*([a-zA-Z])\s*=\s*([a-zA-Z])\s*\+\s*\(\s*([a-zA-Z])\s*\+\s*([a-zA-Z])\s*\)", s)
    if not m: return None
    a,b,c, a2,b2,c2 = m.groups()
    if {a,b,c} != {a2,b2,c2}: return None
    goal = f"∀ {a} {b} {c} : Nat, ({a} + {b}) + {c} = {a} + ({b} + {c})"
    tac  = f"intro {a}; intro {b}; intro {c}; rw [Nat.add_assoc]"
    return goal, tac, ["Std"]

def eq_add_zero_nat(s: str) -> Optional[Tuple[str, str, List[str]]]:
    m1 = re.search(r"\b([a-zA-Z])\s*\+\s*0\s*=\s*\1\b", s)
    if m1:
        a = m1.group(1)
        goal = f"∀ {a} : Nat, {a} + 0 = {a}"
        tac  = f"intro {a}; simp"
        return goal, tac, ["Std"]
    m2 = re.search(r"\b0\s*\+\s*([a-zA-Z])\s*=\s*\1\b", s)
    if m2:
        a = m2.group(1)
        goal = f"∀ {a} : Nat, 0 + {a} = {a}"
        tac  = f"intro {a}; simp"
        return goal, tac, ["Std"]
    return None

def refl_nat(s: str) -> Optional[Tuple[str, str, List[str]]]:
    m = re.search(r"\b([a-zA-Z])\s*=\s*\1\b", s)
    if not m: return None
    a = m.group(1)
    goal = f"∀ {a} : Nat, {a} = {a}"
    tac  = f"intro {a}; rfl"
    return goal, tac, ["Std"]

def true_goal(s: str) -> Optional[Tuple[str, str, List[str]]]:
    if re.search(r"\bTrue\b", s):
        return "True", "exact True.intro", ["Std"]
    return None

def false_imp_false(s: str) -> Optional[Tuple[str, str, List[str]]]:
    if re.search(r"\bFalse\s*→\s*False\b", s):
        return "False → False", "intro h; exact h", ["Std"]
    return None

def impl_refl_prop(s: str) -> Optional[Tuple[str, str, List[str]]]:
    m = re.search(r"\b([A-Z])\s*→\s*\1\b", s)
    if not m: return None
    P = m.group(1)
    goal = f"∀ {P} : Prop, {P} → {P}"
    tac  = f"intro {P}; intro h; exact h"
    return goal, tac, ["Std"]

def and_left(s: str) -> Optional[Tuple[str, str, List[str]]]:
    if re.search(r"\b([A-Z])\s*∧\s*([A-Z])\s*→\s*\1\b", s):
        P,Q = "P","Q"
        goal = f"∀ {P} {Q} : Prop, {P} ∧ {Q} → {P}"
        tac  = f"intro {P}; intro {Q}; intro h; exact h.left"
        return goal, tac, ["Std"]
    return None

DETECTORS = [
    eq_comm_add_nat, eq_comm_mul_nat, eq_assoc_add_nat, eq_add_zero_nat,
    refl_nat, true_goal, false_imp_false, impl_refl_prop, and_left
]

# lean check

def lean_ok(goal: str, tactic: str, imports: List[str], timeout: float) -> Tuple[bool, str]:
    code = "\n".join([*(f"import {m}" for m in imports), "", "set_option maxHeartbeats 200000", f"example : {goal} := by", f"  {tactic}", ""])
    with tempfile.TemporaryDirectory() as td:
        src = os.path.join(td, "Check.lean")
        with open(src, "w", encoding="utf-8") as f:
            f.write(code)
        try:
            r = subprocess.run(["lean", src], capture_output=True, text=True, timeout=timeout)
            return (r.returncode == 0, (r.stderr or "").strip())
        except subprocess.TimeoutExpired:
            return (False, f"timeout>{timeout}s")

# conversion

def convert_record(rec: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    if "goal" in rec and "gold_tactic" in rec:
        imports = rec.get("imports", ["Std"])
        return {"id": rec.get("id", None), "goal": rec["goal"], "gold_tactic": rec["gold_tactic"], "imports": imports}

    s_text   = norm(str(rec.get("text","")))
    s_target = norm(str(rec.get("target","")))

    for src in (s_text, s_target):
        for det in DETECTORS:
            out = det(src)
            if out:
                goal, tac, imps = out
                return {"id": rec.get("id", None), "goal": goal, "gold_tactic": tac, "imports": imps}
    return None

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--np_root", required=True, help="path to naturalproofs dataset saved with load_from_disk")
    ap.add_argument("--out_root", required=True, help="output folder for the converted dataset")
    ap.add_argument("--timeout", type=float, default=4.0, help="lean check timeout in seconds")
    ap.add_argument("--probe_n", type=int, default=50, help="number of random items to recheck for a quick probe")
    ap.add_argument("--seed", type=int, default=1234, help="random seed")
    args = ap.parse_args()

    random.seed(args.seed)

    ds_src = load_from_disk(args.np_root)
    splits_out: Dict[str, List[Dict[str, Any]]] = {}
    skipped_per_split: Dict[str, int] = {}
    kept_per_split: Dict[str, int] = {}

    for split in ds_src.keys():
        kept: List[Dict[str, Any]] = []
        skipped = 0
        for ex in ds_src[split]:
            conv = convert_record(ex)
            if not conv:
                skipped += 1
                continue
            ok, _ = lean_ok(conv["goal"], conv["gold_tactic"], conv["imports"], timeout=args.timeout)
            if ok:
                kept.append(conv)
            else:
                skipped += 1
        splits_out[split] = kept
        skipped_per_split[split] = skipped
        kept_per_split[split] = len(kept)

    if all(len(v) == 0 for v in splits_out.values()):
        raise SystemExit("no convertible examples were found")

    ds_out = DatasetDict({k: Dataset.from_list(v) for k, v in splits_out.items()})
    os.makedirs(args.out_root, exist_ok=True)
    ds_out.save_to_disk(args.out_root)

    # quick probe on validation if present else test else train
    probe_split = "validation" if "validation" in ds_out and len(ds_out["validation"])>0 else (
        "test" if "test" in ds_out and len(ds_out["test"])>0 else "train"
    )
    probe_set = ds_out[probe_split]
    probe_k = min(args.probe_n, len(probe_set))
    ok = 0
    for i in range(probe_k):
        ex = probe_set[i]
        s, _ = lean_ok(ex["goal"], ex["gold_tactic"], ex["imports"], timeout=args.timeout)
        ok += int(s)

    report = {
        "splits": {k: {"kept": kept_per_split[k], "skipped": skipped_per_split.get(k, 0)} for k in splits_out.keys()},
        "out_root": args.out_root,
        "probe_split": probe_split,
        "probe_checked": probe_k,
        "probe_ok": ok
    }
    with open(os.path.join(args.out_root, "conversion_report.json"), "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)
    print(json.dumps(report, indent=2))

if __name__ == "__main__":
    main()